<a href="https://colab.research.google.com/github/Luis-Salgado/Estadistica_y_Probabilidad_para-CD-/blob/main/Pracica_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Desarrolle un programa en Python que genere una arreglo NumPy tridimensional de tama˜ no 5×4×3 con
 valores aleatorios entre 0 y 100. Posteriormente el programa debe encontrar el elemento m´as peque˜no
 y el m´as grande e indicar la ubicaci´ on de dichos elementos dentro del arreglo. Imprima la matriz, los
 valores menor y mayor, as´ ıcomo sus ubicaciones. Guarde su programa en un archivo con extensi´on .py.

In [ ]:
import numpy as np

# Crear un array tridimensional de ejemplo con números aleatorios entre 0 y 100
array_3d_random = np.random.randint(0, 101, (5, 4, 3))

# Encontrar el valor más pequeño
valor_minimo = np.min(array_3d_random)

# Encontrar el valor más grande
valor_maximo = np.max(array_3d_random)

# Encontrar las ubicaciones de esos valores
indice_minimo = np.argmin(array_3d_random)
indice_maximo = np.argmax(array_3d_random)
ubicacion_minimo = tuple(int(i) for i in np.unravel_index(indice_minimo, array_3d_random.shape))
ubicacion_maximo = tuple(int(i) for i in np.unravel_index(indice_maximo, array_3d_random.shape))

print("Array:")
print(array_3d_random)
print(f"El valor más pequeño es {valor_minimo}, ubicado en la posición {ubicacion_minimo}")
print(f"El valor más grande es {valor_maximo}, ubicado en la posición {ubicacion_maximo}")

Array:
[[[76 13  7]
  [86 24 97]
  [97 82 36]
  [95  1 84]]

 [[35  2 57]
  [98 74 82]
  [85  6 91]
  [62 59 41]]

 [[93 98 92]
  [69  9 53]
  [98  3 54]
  [48 22 97]]

 [[63 30 41]
  [21 44 42]
  [30 15 21]
  [11 87 30]]

 [[13 15 84]
  [96 92 59]
  [57  2 88]
  [49 50 42]]]
El valor más pequeño es 1, ubicado en la posición (0, 3, 1)
El valor más grande es 98, ubicado en la posición (1, 1, 0)


2. Dada la matriz tridimensional H:
 H = 1 2 3
 4 5 6 , 7 8 9
 10 11 12
 Calcula la transpuesta de cada ”plano”1 dentro de la matriz tridimensional H. Guarde su programa en
 un archivo con extensi´on .py.

In [ ]:

import numpy as np

# Definir la matriz tridimensional H
H = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Definir la matriz transpuesta HT
HT=np.transpose(H, (0, 2, 1))

#Imprimir resultados
print(f"la matriz original H es:\n{H}")
print('')
print(f"la matriz transpuesta HT es:\n{HT}")



la matriz original H es:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

la matriz transpuesta HT es:
[[[ 1  4]
  [ 2  5]
  [ 3  6]]

 [[ 7 10]
  [ 8 11]
  [ 9 12]]]
